from typing import Protocol

from app.models.domain import (
    ChatMessage,
    Conversation,
    Event,
    EventTask,
    ExperimentCondition,
    ExperimentSession,
    KnowledgeChunk,
    Persona,
    ResearchLog,
    TaskAttempt,
    WikiSource,
)


class RepositoryProtocol(Protocol):
    def find_event_by_name(self, event_name: str) -> Event | None: ...
    def save_event(self, event: Event) -> Event: ...
    def list_events(self) -> list[Event]: ...
    def get_event(self, event_id: str) -> Event | None: ...
    def delete_event(self, event_id: str) -> bool: ...

    def save_wiki_source(self, source: WikiSource) -> WikiSource: ...
    def list_wiki_sources(self, event_id: str) -> list[WikiSource]: ...

    def save_knowledge_chunk(self, chunk: KnowledgeChunk) -> KnowledgeChunk: ...
    def list_knowledge_chunks(self, event_id: str) -> list[KnowledgeChunk]: ...

    def list_conditions(self, active_only: bool = True) -> list[ExperimentCondition]: ...
    def get_condition_by_key(self, condition_key: str) -> ExperimentCondition | None: ...
    def get_condition(self, condition_id: str) -> ExperimentCondition | None: ...
    def save_condition(self, condition: ExperimentCondition) -> ExperimentCondition: ...

    def save_session(self, session: ExperimentSession) -> ExperimentSession: ...
    def get_session(self, session_id: str) -> ExperimentSession | None: ...
    def list_sessions(self) -> list[ExperimentSession]: ...

    def save_event_task(self, task: EventTask) -> EventTask: ...
    def get_event_task(self, task_id: str) -> EventTask | None: ...
    def get_latest_event_task(self, event_id: str) -> EventTask | None: ...
    def list_event_tasks(self, event_id: str) -> list[EventTask]: ...

    def save_task_attempt(self, attempt: TaskAttempt) -> TaskAttempt: ...
    def get_task_attempt(self, attempt_id: str) -> TaskAttempt | None: ...

    def save_persona(self, persona: Persona) -> Persona: ...
    def get_persona(self, persona_id: str) -> Persona | None: ...
    def list_personas(self, event_id: str, active_only: bool = True) -> list[Persona]: ...
    def delete_persona(self, persona_id: str) -> bool: ...

    def save_conversation(self, conversation: Conversation) -> Conversation: ...
    def get_conversation(self, conversation_id: str) -> Conversation | None: ...

    def next_message_sequence(self, conversation_id: str) -> int: ...
    def add_message(self, message: ChatMessage) -> ChatMessage: ...
    def list_messages(self, conversation_id: str) -> list[ChatMessage]: ...

    def log_research(self, log: ResearchLog) -> ResearchLog: ...
    def list_research_logs(self, limit: int = 200) -> list[ResearchLog]: ...

    def increment_view_count(self) -> int: ...
